arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
#output-dir: lib/src/l10n (optional define an output directory for generated files)
#synthetic-package: false
#nullable-getter: false