name: sentit
description: Flutter application.
version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  http: ^0.13.5
  json_annotation: ^4.8.1
  obs_foundation:
    git:
      url: ssh://application-lifecycle.factory.orange-business.com:22/ads/DX2/practice-flutter/_git/obs_foundation
      ref: refs/tags/v1.2.2
  shared_preferences: ^2.2.2
  flutter_localization: ^0.2.0
  intl: ^0.18.1
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  go_router: ^13.2.0
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  flutter_svg: ^2.0.9
  cloud_firestore: ^4.15.5

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.21.7
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  custom_lint: ^0.6.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
